package com.mycompany.pp2;

import java.awt.Color;

/**
 *
 * @author gabob
 */
public class PantallaJuego extends PantallaMadre {

    /**
     * Creates new form PantallaMadre
     */
    public PantallaJuego() {
        initComponents();
        personalizarPantalla();
        setCustomIcon(this, "images/MvDCicon.png");
        imageStretcher(ImgIzq);
        imageStretcher(ImgDer);
    }
    
    private void personalizarPantalla() {
        // Cambiar el título de la ventana
        setTitle("Partida en progreso... - MARVEL VS DC");

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreIzq = new javax.swing.JLabel();
        ImgIzq = new javax.swing.JLabel();
        BtnIzq = new javax.swing.JButton();
        ProgressBarIzq = new javax.swing.JProgressBar();
        NombreDer = new javax.swing.JLabel();
        ImgDer = new javax.swing.JLabel();
        BtnDer = new javax.swing.JButton();
        ProgressBarDer = new javax.swing.JProgressBar();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(251, 252, 254));
        setMinimumSize(new java.awt.Dimension(931, 589));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreIzq.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 26)); // NOI18N
        NombreIzq.setText("Spider-Man");
        getContentPane().add(NombreIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        ImgIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ornstein.png"))); // NOI18N
        ImgIzq.setText("jLabel2");
        getContentPane().add(ImgIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 290, 440));

        BtnIzq.setBackground(new java.awt.Color(53, 152, 155));
        BtnIzq.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        BtnIzq.setForeground(new java.awt.Color(51, 51, 51));
        BtnIzq.setText("Atacar");
        BtnIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIzqActionPerformed(evt);
            }
        });
        getContentPane().add(BtnIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 100, 40));
        getContentPane().add(ProgressBarIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, 10));

        NombreDer.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 26)); // NOI18N
        NombreDer.setText("Spider-Man");
        getContentPane().add(NombreDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, -1));

        ImgDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smough.png"))); // NOI18N
        ImgDer.setText("jLabel2");
        getContentPane().add(ImgDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 290, 440));

        BtnDer.setBackground(new java.awt.Color(227, 150, 92));
        BtnDer.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        BtnDer.setForeground(new java.awt.Color(51, 51, 51));
        BtnDer.setText("Atacar");
        BtnDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDerActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 100, 40));
        getContentPane().add(ProgressBarDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, -1, 10));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BgJuego.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIzqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnIzqActionPerformed

    private void BtnDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PantallaJuego().setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton BtnDer;
    private javax.swing.JButton BtnIzq;
    private javax.swing.JLabel ImgDer;
    private javax.swing.JLabel ImgIzq;
    private javax.swing.JLabel NombreDer;
    private javax.swing.JLabel NombreIzq;
    private javax.swing.JProgressBar ProgressBarDer;
    private javax.swing.JProgressBar ProgressBarIzq;
    // End of variables declaration//GEN-END:variables
}
