package com.mycompany.pp2;

import static com.mycompany.pp2.PantallaMadre.imageStretcher;
import static com.mycompany.pp2.PantallaMadre.setCustomIcon;
import com.mycompany.pp2.clases.Heroe;
import com.mycompany.pp2.clases.Personaje;
import com.mycompany.pp2.clases.Villano;
import com.mycompany.pp2.clases.Antiheroe;
import java.awt.Color;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author gabob
 */
public class PantallaJuego extends PantallaMadre {
    private Personaje personajeIzq;
    private Personaje personajeDer;
    /**
     * Creates new form PantallaMadre
     */
    public PantallaJuego(Personaje personajeIzq, Personaje personajeDer) {
        this.personajeIzq = personajeIzq;
        this.personajeDer = personajeDer;
        
        initComponents();
        personalizarPantalla();
        setCustomIcon(this, "images/MvDCicon.png");
        imageStretcher(ImgIzq);
        imageStretcher(ImgDer);
        
        actualizarPantalla();
    }

    private void actualizarPantalla() {
        NombreIzq.setText(personajeIzq.getPseudonimo());
        NombreDer.setText(personajeDer.getPseudonimo());

        ImgIzq.setIcon(new ImageIcon(getClass().getResource(personajeIzq.getFotografia())));
        ImgDer.setIcon(new ImageIcon(getClass().getResource(personajeDer.getFotografia())));

        ProgressBarIzq.setValue(((Heroe) personajeIzq).getVidaPorcentaje());
        ProgressBarDer.setValue(((Villano) personajeDer).getVidaPorcentaje());
    }
    
    private void verificarFinDeJuego() {
        if (((Heroe) personajeIzq).getVida() <= 0) {
            JOptionPane.showMessageDialog(this, personajeDer.getPseudonimo() + " ha ganado!");
            this.dispose();
        } else if (((Villano) personajeDer).getVida() <= 0) {
            JOptionPane.showMessageDialog(this, personajeIzq.getPseudonimo() + " ha ganado!");
            this.dispose();
        }
    }
    
    private void personalizarPantalla() {
        // Cambiar el título de la ventana
        setTitle("Partida en progreso... - MARVEL VS DC");

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreIzq = new javax.swing.JLabel();
        ImgIzq = new javax.swing.JLabel();
        BtnIzq = new javax.swing.JButton();
        ProgressBarIzq = new javax.swing.JProgressBar();
        NombreDer = new javax.swing.JLabel();
        ImgDer = new javax.swing.JLabel();
        BtnDer = new javax.swing.JButton();
        ProgressBarDer = new javax.swing.JProgressBar();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(251, 252, 254));
        setMinimumSize(new java.awt.Dimension(931, 589));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreIzq.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 26)); // NOI18N
        NombreIzq.setText("Spider-Man");
        getContentPane().add(NombreIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        ImgIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ornstein.png"))); // NOI18N
        ImgIzq.setText("jLabel2");
        getContentPane().add(ImgIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 290, 440));

        BtnIzq.setBackground(new java.awt.Color(53, 152, 155));
        BtnIzq.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        BtnIzq.setForeground(new java.awt.Color(51, 51, 51));
        BtnIzq.setText("Atacar");
        BtnIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIzqActionPerformed(evt);
            }
        });
        getContentPane().add(BtnIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 100, 40));
        getContentPane().add(ProgressBarIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, 10));

        NombreDer.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 26)); // NOI18N
        NombreDer.setText("Spider-Man");
        getContentPane().add(NombreDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, -1));

        ImgDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smough.png"))); // NOI18N
        ImgDer.setText("jLabel2");
        getContentPane().add(ImgDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 290, 440));

        BtnDer.setBackground(new java.awt.Color(227, 150, 92));
        BtnDer.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        BtnDer.setForeground(new java.awt.Color(51, 51, 51));
        BtnDer.setText("Atacar");
        BtnDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDerActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 100, 40));
        getContentPane().add(ProgressBarDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, -1, 10));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BgJuego.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIzqActionPerformed
        if (personajeDer instanceof Heroe) {
            ((Heroe) personajeDer).recibirAtaque(personajeIzq);
            ProgressBarDer.setValue(((Heroe) personajeDer).getVidaPorcentaje());
        } else if (personajeDer instanceof Villano) {
            ((Villano) personajeDer).recibirAtaque(personajeIzq);
            ProgressBarDer.setValue(((Villano) personajeDer).getVidaPorcentaje());
        } else if (personajeDer instanceof Antiheroe) {
            ((Antiheroe) personajeDer).recibirAtaque(personajeIzq);
            ProgressBarDer.setValue(((Antiheroe) personajeDer).getVidaPorcentaje());
        }
        verificarFinDeJuego();
    }//GEN-LAST:event_BtnIzqActionPerformed

    private void BtnDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDerActionPerformed
        if (personajeIzq instanceof Heroe) {
            ((Heroe) personajeIzq).recibirAtaque(personajeDer);
            ProgressBarIzq.setValue(((Heroe) personajeIzq).getVidaPorcentaje());
        } else if (personajeIzq instanceof Villano) {
            ((Villano) personajeIzq).recibirAtaque(personajeDer);
            ProgressBarIzq.setValue(((Villano) personajeIzq).getVidaPorcentaje());
        } else if (personajeIzq instanceof Antiheroe) {
            ((Antiheroe) personajeIzq).recibirAtaque(personajeDer);
            ProgressBarIzq.setValue(((Antiheroe) personajeIzq).getVidaPorcentaje());
        }
        verificarFinDeJuego();
    }//GEN-LAST:event_BtnDerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        // Crear personajes de prueba para iniciar el juego
        Personaje personaje1 = new Heroe("Batman", new Date(), "Gotham", "/images/batman.png",
                Personaje.TipoPersonaje.HEROE, "Batman", "/images/batman.png", 
                Personaje.TipoOrigen.META_HUMANO, Personaje.TipoFranquicia.DC, 
                80, 70, 85, 60);

        Personaje personaje2 = new Villano("Joker", new Date(), "Gotham", "/images/joker.png",
                Personaje.TipoPersonaje.VILLANO, "Joker", "/images/joker.png", 
                Personaje.TipoOrigen.META_HUMANO, Personaje.TipoFranquicia.DC, 
                75, 65, 90, 50);

        java.awt.EventQueue.invokeLater(() -> {
            new PantallaJuego(personaje1, personaje2).setVisible(true);
        });
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PantallaJuego(personaje1, personaje2).setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton BtnDer;
    private javax.swing.JButton BtnIzq;
    private javax.swing.JLabel ImgDer;
    private javax.swing.JLabel ImgIzq;
    private javax.swing.JLabel NombreDer;
    private javax.swing.JLabel NombreIzq;
    private javax.swing.JProgressBar ProgressBarDer;
    private javax.swing.JProgressBar ProgressBarIzq;
    // End of variables declaration//GEN-END:variables
}
