package com.mycompany.pp2;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.*;

/**
 *
 * @author gabob
 */
public class PantallaMadre extends javax.swing.JFrame {

    /**
     * Creates new form PantallaMadre
     */
    public PantallaMadre() {
        initComponents();
        
        //Ponerle color al JLabel del fondo (Gris oscuro)
        Color ColorFondo = new Color (251, 252, 254);
        setBackgroundColor(this ,ColorFondo);
        
        //Configurando el ícono del programa
        setCustomIcon(this, "images/MvDCicon.png");
    }
    
    /**
     * Ajusta el tamaño de la imagen para que se adapte al JLabel proporcionado.
     * 
     * @param stretcyImage JLabel al que se ajustará la imagen.
     */
    public static void imageStretcher(JLabel stretcyImage) {
    Icon i = stretcyImage.getIcon();
    ImageIcon icon = (ImageIcon) i;
    Image image = icon.getImage().getScaledInstance(stretcyImage.getWidth(), stretcyImage.getHeight(), Image.SCALE_SMOOTH);
    stretcyImage.setIcon(new ImageIcon(image));
    }
    
    /**
     * Cambia el color de fondo del JFrame principal.
     * 
     * @param frame JFrame cuyo fondo se desea cambiar.
     * @param color Color que se aplicará como fondo.
     */
    public static void setBackgroundColor(JFrame frame, Color color) {
        frame.getContentPane().setBackground(color);
    }
    
    /**
     * Establece un ícono personalizado en un JFrame utilizando un recurso en la ruta especificada.
     * 
     * @param frame JFrame al que se le asignará el ícono.
     * @param path Ruta del recurso de la imagen del ícono.
     * @throws IllegalArgumentException Si el frame o la ruta son nulos o vacíos.
     */
    public static void setCustomIcon(JFrame frame, String path) {
        if (frame == null || path == null || path.isEmpty()) {
            throw new IllegalArgumentException("El frame o la ruta del recurso no pueden ser nulos o vacíos.");
        }
        frame.setIconImage(Toolkit.getDefaultToolkit().getImage(PantallaMadre.class.getResource("/" + path))
        );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(251, 252, 254));
        setMinimumSize(new java.awt.Dimension(931, 589));
        setPreferredSize(new java.awt.Dimension(931, 589));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaMadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaMadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaMadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaMadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PantallaMadre().setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
